### ISSUE TITLE
Can we load model with transformer library?

### ISSUE THREAD

**Issue by ithieund** [nlp-uoregon/trankit#10]
Hi @minhvannguyen ,
Can I load the model using this coding style?
`import torch
from transformers import AutoModel, AutoTokenizer

model = AutoModel.from_pretrained("trankit")
tokenizer = AutoTokenizer.from_pretrained("trankit", use_fast=False)`

Thank you.

**Comment by minhvannguyen** [comment]
Hi @ithieund,
Thanks for asking. 
Trankit is not a language model like multilingual BERT or XLM-Roberta, so it's not possible to use the library in your suggested way. 
If you want to use an adapter-based transformer encoder, we suggest you looking at the `Base_Model` class in [this file](https://github.com/nlp-uoregon/trankit/blob/master/trankit/models/base_models.py), where you can find how to combine a pretrained transformer with a set of adapter weights.
Please let me know if that answers your question.
Thanks

**Comment by ithieund** [comment]
Hi @minhvannguyen ,
Thank you for your quick response.
I'll try that.
