### ISSUE TITLE
Running Evals on Sentence Segmentation

### ISSUE THREAD

**Issue by kpister** [nlp-uoregon/trankit#11]
Very neat project! I am trying to understand the quality of trankit's sentence segmentation. I see the evals here: https://trankit.readthedocs.io/en/latest/performance.html#universal-dependencies-v2-5, but the results aren't very clear to me. Each column is simply a percentage, are these accuracy scores? F1-scores?

Additionally I'd like to run an eval against [nltk's Punkt](https://www.kite.com/python/docs/nltk.punkt) sentence segmentation model to see which I should use. Is the code that generate your evals public?

Thanks.

**Comment by minhvannguyen** [comment]
Hi @kpister,
Thanks for the question.
The reported scores for sentence segmentation are F1 scores computed by using the official evaluation script of the CoNLL 2018 Shared Task, which is publicly available [here](https://universaldependencies.org/conll18/evaluation.html) . 
To run the evaluation script, the system and gold sentence segmentations should be organized into the [CoNLL-U format](https://universaldependencies.org/format.html). To get the Universal Dependencies datasets, you can download them [here](https://universaldependencies.org/).
Thanks.

**Comment by kpister** [comment]
Thanks for the response.
