### ISSUE TITLE
How to download resources manually

### ISSUE THREAD

**Issue by eliasyin** [nlp-uoregon/trankit#14]
Due to the network is poor, when I run the code
```python
from trankit import Pipeline
p = Pipeline('english')
```
It's very slow and often break off. `41.6M/1.12G [07:26<3:17:34, 90.6kB/s]`
So, I wander if there are methods that I can manually download the resources.

**Comment by minhhdvn** [comment]
Hi @eliasyin,
This part is for downloading `xlm-roberta-base` pretrained model which is provided by the `transformers` library. You can look at [this discussion](https://github.com/huggingface/transformers/issues/856) to see how to manually download it. Once the `xlm-roberta-base` model files are downloaded, please put them at `./cache/trankit/xlm-roberta-base` which is the default cache directory.
Thanks.

**Comment by eliasyin** [comment]
Thank you @minhhdvn
