### ISSUE TITLE
Dependency parsing not exactly

### ISSUE THREAD

**Issue by princess96tq** [nlp-uoregon/trankit#16]
When I try to test some case in http://nlp.uoregon.edu/trankit, I found a wrong case, be like this:
"Joe Biden is my father"
![image](https://user-images.githubusercontent.com/18047493/113967182-719d7800-986b-11eb-9aef-d7dc5ea8deb7.png)
I think in this sentence, the root will be "is". It seems that in most cases returns root is a 'NOUN' token

**Comment by minhhdvn** [comment]
Hi @princess96tq,
Thanks for asking.
We think trankit is doing it right. 
We looked into the training data and observed that the root for the sentences with the structure "X be Y" is usually the noun inside Y. You can also refer to other toolkits' demo (e.g., http://corenlp.run/, http://stanza.run/) to see that they also annotated "father" as the root for your sentence.
