### ISSUE TITLE
Vietnamese word tokenization seems broken at certain situations

### ISSUE THREAD

**Issue by AkiLotus** [nlp-uoregon/trankit#18]
This is not too common of a case but it sometimes happens.

Original sentence:
"nhắn vào số của ngõ vạn phúc là gửi lịch sử thanh toán không"
Tokenized sentence (for convenience, phonetics assigned as one word are linked with underscore(s)):
"nhắn vào số của ngo ~_vạn_ph ú c là gửi lịc h_sử_thanh_t oán_kh ông"

As you can see, the phonetics themselves were oddly splitted out, even the tone got splitted also.

Also, when I try to recreate this on the demo, it just popped up "Connection error!" (as in screenshot), but the default example still works, denoting the demo system still functions properly on normal cases but this.

Please look into this problem. Thank you.

![image](https://user-images.githubusercontent.com/41355100/114525729-de32c100-9c35-11eb-8ba2-0e81ee0f0e7a.png)

**Comment by minhhdvn** [comment]
Hi @AkiLotus,
Thank you for reporting this.
We will look into it and let you know later.
Thanks.

**Comment by AkiLotus** [comment]
So I think there would be some crucial information you might need for this issue.
I typed that sentence again by a common Vietnamese inputter, and it segmented properly. My bet is that, the text I mentioned above was encoded in a weird way, maybe separating the base character and the tones/symbols of it, therefore bugging the segmenter of the system.

Thanks for taking time on this issue.
