### ISSUE TITLE
Performance issue on cpu only machines

### ISSUE THREAD

**Issue by mcolella89** [nlp-uoregon/trankit#19]
Hi all,
I'm trying to run Trankit on a server which doesn't have gpu available, so it seems slower than, for example, Stanford tools for NER and tokenization by x10 factor (0.500ms vs 5sec on NER english task, corpus is 2000 tokens circa).

I was wondering if
1) loading a different model other than Roberta-base could help? such as [distilRoberta-base](https://huggingface.co/distilroberta-base)

2) running Trankit in manual mode could help too?

Do you have any other suggestion on how to enhance performance on cpu only servers? Thanks!

Also, at the start of model loading, I got this message line appears twice:
`Loading pretrained XLM-Roberta, this may take a while...`
`Loading pretrained XLM-Roberta, this may take a while...`
something wrong with my implementation or does it work as intended? thanks

**Comment by minhhdvn** [comment]
Hi @mcolella89,
Thanks for your questions.
For 1., this is a good suggestion on using a distilled transformer. We'll consider it in the future versions of trankit.
For 2., by "manual mode", do you mean "running Trankit on a GPU device"?
For CPU speed, we think it might help if you could try increasing the batch sizes for trankit. Below is an example for doing so:
```
from trankit import Pipeline
p = Pipeline('english')
p._tokbatchsize = 4
p._tagbatchsize = 24
```
where `_tokbatchsize` is the number documents processed at the same time for the sentence splitter and the tokenizer of trankit, and `_tagbatchsize` is the number of sentences processed at the same time for the part-of-speech tagger, the dependency parser, and the named entity recognizer of trankit. By default, we set `p._tokbatchsize = 2` and `p._tagbatchsize = 12` for CPU running.
We hope this can help.
Thanks.
