### ISSUE TITLE
Question: running in parallel

### ISSUE THREAD

**Issue by JulesBelveze** [nlp-uoregon/trankit#2]
Hey guys,

Starting to use your library, which is pretty cool! Thanks a lot !
However, I'm trying to process a lot of document ~400k and as you can guess it will take quite some time 😅 .
I'm working with pandas dataframe and I tried to use `pandarallel` to try running things in parallel but I didn't manage to have it to work. Seemed like it was stuck forever..

Do you have any if there's a way I could leverage parallelisation (or anything else other than GPU) to reduce computation time?

Thanks in advance!

**Comment by minhvannguyen** [comment]
> Hey guys,
> 
> Starting to use your library, which is pretty cool! Thanks a lot !
> However, I'm trying to process a lot of document ~400k and as you can guess it will take quite some time 😅 .
> I'm working with pandas dataframe and I tried to use `pandarallel` to try running things in parallel but I didn't manage to have it to work. Seemed like it was stuck forever..
> 
> Do you have any if there's a way I could leverage parallelisation (or anything else other than GPU) to reduce computation time?
> 
> Thanks in advance!
Thanks for letting us know your issue.

Could you provide the part of your code that uses Trankit, so that we can know which function has been used, and get an overall picture of what happened? We guess that your code can run without error but it seems not stopping, right? If not, could you provide some log or whatever's printed out? It would be very helpful.

Thanks

**Comment by JulesBelveze** [comment]
Hey @minhvannguyen thanks for the quick answer.
Here is a snippet of the code I use:

from pandarallel import pandarallel
pandarallel.initialize()

```
class DatasetCreator:
    def __init__(self, path_to_file):
        self.path_to_file = path_to_file
        self.pipeline = Pipeline("english")
        self.prepare_data()

    def prepare_data(self):
        df = pd.read_csv(self.path_to_file)
        logging.info("Extracting entities from 'text' and 'title'.")
        df["text_entities"] = df["text"].parallel_apply(lambda x: self.get_entities(x))
              ...

    def get_entities(self, text: str):
        entities = []
        try:
            tagged_doc = self.pipeline.ner(text)
            for sentence in tagged_doc["sentences"]:
                for t in sentence["tokens"]:
                    if t["ner"] != "O":
                        if any([elt == t["ner"][0] for elt in ["U", "B", "S"]]):
                            entities.append(t["text"])
                        if "I" == t["ner"][0] or "E" == t["ner"][0]:
                            entities[-1] += " {}".format(t["text"])
        except (RuntimeError, IndexError) as e:
            print("Error in :{}\n".format(text))
            print("Error message: {}\n\n".format(str(e)))

        return list(set(entities))

creator = DatasetCreator("data.csv")
```

I tried it on a very sample dataframe and basically nothing happens, it gets stuck forever... I don't know if this comes from `pandarallel` or not.. At first I thought the problem might come from the fact that the `Pipeline` is instantiated as an attribute but the same phenomenon occurs without using an object.
Sorry I cannot provide a lot more info, this is all I have 😅

**Comment by minhvannguyen** [comment]
Hi @JulesBelveze,
According to this page: https://github.com/nalepae/pandarallel, it seems that pandarallel is created for parallelizing CPU processes only. 
In your code, the Trankit pipeline is initialized like this: `self.pipeline = Pipeline("english")`
By default, this would make the pipeline run on GPU if a GPU device is available.
To solve the problem, I think you can consider one of the following:
1. If running on CPU is your preference, you can initialize a CPU pipeline, which can be done as follows: 
`self.pipeline = Pipeline("english", gpu=False)`

2. Another possible way is to separate Trankit from pandarallel by defining your `prepare_data()` function like this:
`def prepare_data(self):
        df = pd.read_csv(self.path_to_file)
        logging.info("Extracting entities from 'text' and 'title'.")
        df["text_entities"] = self.get_entities(df["text"])
`
Please let us know if you can solve your problem.

Thanks

**Comment by JulesBelveze** [comment]
Hi @minhvannguyen,
Thank you for your help!

The first option did not solve the problem.. Separating `trankit` and `pandarallel` actually works but then it does not leverage multi-threading...
I finally ran my experiment on a GPU and everything went well 😄 

However, I think that multi-threading could be a nice feature to integrate later!
