### ISSUE TITLE
Trankit pipeline does redundant operations (mostly loading adapter weights)

### ISSUE THREAD

**Issue by AkiLotus** [nlp-uoregon/trankit#20]
[In the pipeline source code](https://github.com/nlp-uoregon/trankit/blob/master/trankit/pipeline.py), scripts indicated that the _load_adapter_weights method is called nearly *every* main method (posdep, ner, etc.). For batch tagging, this could prove problematic, as the pipeline should be supposed to load just once, if already loaded at a previous time then the former method should not be called again in order to save runtime.
Please look into this.
Thank you.

**Comment by furyphoenix** [comment]
Agree no more. The performance was severely pulled down especially when tagging massive short texts. It took about 40 minutes to process 10K tweets in Tesla V100 GPU,  but only 2 min if I concat all tweets to one long string.
Please look into this.
Thank you.

**Comment by furyphoenix** [comment]
I did some more performance tests.
I added a Boolean param in the token(), ner(), and pos() functions somewhat like this:
______________________________________________________________
def _posdep_sent(self, in_sent, is_load_weights=True):  # assuming input is a sentence
       ... ...
      # load weights of tagger into the combined model
        if is_load_weights:
            self._load_adapter_weights(model_name='tagger')
     ... ...
____________________________________________________________

I processed 10K tweets with setting load_weights = True only once. The time consumption drops down from 40 minutes to about 10 minutes. But it is still 4~5 times longer than concating all tweets to one string.
May need further optimizations.

**Comment by minhhdvn** [comment]
Hi @AkiLotus  and @furyphoenix,
Thank you for your comments and suggestions.
We're addressing this issue and let you know when it's done.

**Comment by jsteggink** [comment]
@minhhdvn Any update on this issue?
