### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by ogencoglu** [nlp-uoregon/trankit#21]
Great library! 

Can you provide the detailed documentation of the API? For example, what are the inputs/fields of the `Pipeline` class/function and their meanings etc. 

`Pipeline(lang='english', gpu=True, cache_dir='./cache')`

**Comment by minhhdvn** [comment]
Hi @ogencoglu,
Thanks for the questions.
Trankit's documentation page is available here:
https://trankit.readthedocs.io/en/latest/overview.html#initialize-a-pipeline
