### ISSUE TITLE
Understanding the token fields

### ISSUE THREAD

**Issue by kpister** [nlp-uoregon/trankit#23]
The documentation mentions some information about each of the token fields:
```
{
  'text': 'Hello! This is Trankit.',  # input string
  'sentences': [ # list of sentences
    {
      'id': 2,  # sentence index
      'text': 'This is Trankit.',  'dspan': (7, 23), # sentence span
      'tokens': [ # list of tokens
        {
          'id': 1, # token index
          'text': 'This',  # text form of the token
          'upos': 'PRON',  # UPOS tag of the token
          'xpos': 'DT',    # XPOS tag of the token
          'feats': 'Number=Sing|PronType=Dem', # morphological feature of the token
          'head': 3,  # index of the head token
          'deprel': 'nsubj', # dependency relation for the token
          'dspan': (7, 11), # document-level span of the token
          'span': (0, 4) # sentence-level span of the token
        },
       ...
```
But finding information about what the `xpos` and `deprel` fields _mean_ is difficult. `upos` is a bit easier to find online. What are valid values? Is there documentation that could be linked to describe them?

Thanks!

Edit: just want to add that I found the UPOS info here: https://universaldependencies.org/u/pos/index.html, but it specifies that XPOS is specific to each language. How should I go about finding more on that?

**Comment by minhhdvn** [comment]
Hi @kpister,
Thanks for the questions.
XPOS tags are indeed language-specific and they vary a lot across the languages. We looked into the universaldependencies.org and didn't find a documentation for the XPOS neither.
To access the full list of possible XPOS tags for a specific language, you could use the vocabulary file attached to each pretrained pipeline of trankit. For example, you could download the English pretrained pipeline via this link: 
`http://nlp.uoregon.edu/download/trankit/v1.0.0/xlm-roberta-base/english.zip`
The possible XPOS tags for English can be then accessed by reading extracting the zip file, loading `english.vocabs.json`, and accessing the filed `"xpos"`.
With the possible XPOS tags, we think it's possible to take their identities and do some search for their meanings.
