### ISSUE TITLE
The result from demo（http://nlp.uoregon.edu/trankit）is different from python's trankit==1.0.1

### ISSUE THREAD

**Issue by call22** [nlp-uoregon/trankit#24]
sentence: "如果一名操作工夜间进入围沿内打扫卫生时不注意，可能迈入坑内造成腿部轻微擦伤，到医务室处理后继续正常工作。"
![image](https://user-images.githubusercontent.com/39378868/117683899-156da100-b1e7-11eb-81a1-259099788c5c.png)
![image](https://user-images.githubusercontent.com/39378868/117683928-1bfc1880-b1e7-11eb-82bd-44f7709bf8f0.png)

python code:
`from trankit import Pipeline
p = Pipeline('chinese', gpu=False)
dependencies = p.posdep(sentence, is_sent=True)`

Is there any different between demo's website and python's package?

**Comment by minhhdvn** [comment]
Hi @call22,
Thanks for the questions.
We think the difference is due to the fact that the demo website is running trankit on GPU while you're runing trankit on CPU. Difference devices for running a pipeline could sometimes result in slightly different outputs.
