### ISSUE TITLE
how can i

### ISSUE THREAD

**Issue by call22** [nlp-uoregon/trankit#25]
When I use trankit to calculate the dependency parsing of chemical hazard sentences. There are many proper nouns here, but trankit cannot identify them correctly sometimes.
eg:
![image](https://user-images.githubusercontent.com/39378868/118388101-edea5e80-b654-11eb-8839-ca8ae58f41aa.png)
![image](https://user-images.githubusercontent.com/39378868/118388114-ff336b00-b654-11eb-9c4e-4dcd603b8fa6.png)
Actually，the word ‘工扶' does not exist in Chinese dictionary. 
So, is there a way to solve this problem? Thanks very much!

**Comment by minhhdvn** [comment]
Hi @call22,
Thanks for the questions.
Could you tell us which pipeline that you used to parse the sentence?
For Chinese, trankit provides two pipelines, one for Simplified Chinese, the other for Traditional Chinese.

**Comment by call22** [comment]
Hi~@minhhdvn ，
Thank you for your answer. 
I use Chinese Simplified pipeline to parse the sentence. But I tried Traditional Chinese and Classical Chinese pipeline, both of them didn't work well.
