### ISSUE TITLE
Cannot import Pipeline

### ISSUE THREAD

**Issue by call22** [nlp-uoregon/trankit#29]
I install trankit 1.1.0 with python 3.7. But I got ImportError when import Pipeline.
![image](https://user-images.githubusercontent.com/39378868/125161808-0c815780-e1b7-11eb-83dd-466b191359d5.png)

The code is copied from https://trankit.readthedocs.io/en/latest/news.html
![image](https://user-images.githubusercontent.com/39378868/125161873-6f72ee80-e1b7-11eb-85af-2aa7007f14fe.png)

**Comment by abcdenis** [comment]
Is `/home/lyf/hsw/try/trankit.py` your sample file?
If yes, try to rename it to `my_test_of_trankit.py` and run again.
