### ISSUE TITLE
error on "from trankit import Pipeline "

### ISSUE THREAD

**Issue by mzolfaghari** [nlp-uoregon/trankit#3]
Thanks for providing this great toolkit. But, I cannot import Pipeline and get the following error:
`ImportError: cannot import name '_BaseLazyModule' from 'transformers.file_utils'
`

It could be because of the conflict in versions. When I did "pip install trankit", I got this error at the end:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.2.1 requires tokenizers==0.9.4, but you have tokenizers 0.9.3 which is incompatible.
Successfully installed tokenizers-0.9.3
```

I really appreciate your help on this.

**Comment by minhvannguyen** [comment]
Hi @mzolfaghari,
Have you tried solving the conflict by installing the expected version for `tokenizers`? 
To do it, you can use the command `pip install tokenizers==0.9.4`.
Please let us know if you can solve the problem.
Thanks

**Comment by mzolfaghari** [comment]
Yes I tried that also. Then I get the following error:

`Collecting tokenizers==0.9.4
  Using cached tokenizers-0.9.4-cp38-cp38-manylinux2010_x86_64.whl (2.9 MB)
Installing collected packages: tokenizers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.9.3
    Uninstalling tokenizers-0.9.3:
      Successfully uninstalled tokenizers-0.9.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
adapter-transformers 1.1.1 requires tokenizers==0.9.3, but you have tokenizers 0.9.4 which is incompatible.`

**Comment by mzolfaghari** [comment]
Ok. Problem solved. I've created a new environment and just installed `python`, `torch` and `trankit`. Now it's working. In previous environment, I had installed `transformers` too, which cause incompatibility.

**Comment by minhvannguyen** [comment]
Hi @mzolfaghari,
Thanks for sharing it. We think this would be really useful for other users as well.

**Comment by jbrry** [comment]
Hi, I think there is currently some blocking issue with some of the current packages. I am getting an `ImportError` in a freshly installed environment. To reproduce:

```
conda create -n trankit python=3.7
conda activate trankit
pip install trankit==1.0.1
```

and then running my script which uses 

```
import trankit
from trankit import Pipeline

# initialize a trainer for the task
trainer = trankit.TPipeline(
    training_config={
    'category': args.category,
    'task': args.task,
    'save_dir': args.save_dir,
    'train_txt_fpath': args.train_txt,
    'train_conllu_fpath': args.train_conllu,
    'dev_txt_fpath': args.dev_text,
    'dev_conllu_fpath': args.dev_conllu
    }
)
```
results in the error:

```
Traceback (most recent call last):
  File "scripts/trankit.py", line 2, in <module>
    import trankit
  File "/home/jbarry/IWPT-2021-shared-task/scripts/trankit.py", line 3, in <module>
    from trankit import Pipeline
ImportError: cannot import name 'Pipeline' from 'trankit' (/home/jbarry/IWPT-2021-shared-task/scripts/trankit.py)

```

**Comment by Ramyavs1291** [comment]
> Ok. Problem solved. I've created a new environment and just installed `python`, `torch` and `trankit`. Now it's working. In previous environment, I had installed `transformers` too, which cause incompatibility.

Can you provide details on new environmen setup . i am a beginner and i face same issue.
