### ISSUE TITLE
Training a model for pre-tagged data

### ISSUE THREAD

**Issue by amir-zeldes** [nlp-uoregon/trankit#30]
Hi and thanks for making this toolkit available! 

I wanted to ask whether it's possible to train a model to predict morphology (FEATS) and/or lemmatization based on pre-tagged text (for example POS tags already in a CoNLL-U input file)?

**Comment by Bachstelze** [comment]
Have a look at the training documentation: https://trankit.readthedocs.io/en/latest/training.html
You could try to train a customized pipeline.
