### ISSUE TITLE
Add a new pretrained model for Arabic...

### ISSUE THREAD

**Issue by oterrier** [nlp-uoregon/trankit#31]
... based on [UD Arabic NYUAD](https://universaldependencies.org/treebanks/ar_nyuad/index.html) which has a commercial friendly license CC BY-SA 4.0 compared to the [Arabic-PADT UD](https://universaldependencies.org/treebanks/ar_padt/index.html) which is under CC BY-NC-SA 3.0
NYUAD is also much bigger

It could be a very interesting resource

Best Regards

Olivier Terrier

**Comment by minhhdvn** [comment]
Thank you for letting us know.
We'll look at it and see how we can use it.
