### ISSUE TITLE
Torch version issue

### ISSUE THREAD

**Issue by kpister** [nlp-uoregon/trankit#33]
I was having an issue using trankit with my GPU since I had an incompatible version of pytorch (`1.9.0+cu111`).

trankit currently requires `torch<1.8.0,>=1.6.0`.

Is there a reason for this dependency lock or could it be expanded to include `torch==1.9.0`? I've built from source with `1.9.0` and everything seems to be working. I'd be happy to make a PR with the version bump.

**Comment by minhhdvn** [comment]
Hi @kpister,
Thanks for raising the issue.
The reason for setting the upper bound for the version of torch is that we encountered some errors with `torch==1.8.0`. It would be helpful if you could give us a hand on this and make a PR.
Thanks.

**Comment by kpister** [comment]
Do you remember what the error was so I can try to reproduce? 
On `torch==1.9.0`, I've run  `test_all` with `xlm-roberta-base` and it is passing 87/91 tests. 
`test_training` requires the training data `train.bio` which I don't see linked from the repo. Is that somewhere I could easily download?
