### ISSUE TITLE
 How to use my own word segmentation when doing part-of-speech tagging？

### ISSUE THREAD

**Issue by CrazyCharles6** [nlp-uoregon/trankit#49]

**Comment by minhhdvn** [comment]
Hi @CrazyCharles6,
Thanks for letting us know.
You can use your own word segmentation by feeding tokenized input to the tagger of Trankit.
Please refer to this page for examples and tutorials:
https://trankit.readthedocs.io/en/latest/posdep.html#pretokenized-input
Thanks
