### ISSUE TITLE
Compatibility issue when using with newer Transformers library

### ISSUE THREAD

**Issue by CaoHoangTung** [nlp-uoregon/trankit#5]
I'm running into an issue when trying to use trankit in a project which use a new version of huggingface transformers library. Trankit depends on adapter-transformers, which cannot be simutanously used with transformers

**Comment by minhvannguyen** [comment]
Hi @CaoHoangTung,
Thanks for pointing it out.
`adapter-transformers` is built on top of `transformers` and the current implementation of the `adapter-transformers` indeed causes the compatibility issue with `transformers` sometimes. For now, as `trankit` depends on `adapter-transformers` so we are not able to solve this issue ourselves. We have a plan to separate `trankit` from `adapter-transformers` and hopefully this would solve the problem.
Thanks.

**Comment by loukey** [comment]
Hi @minhhdvn, is that problem fixed? I still can't use transkit with transformers because of the version of adapter-transformers.

**Comment by minhhdvn** [comment]
Hi @loukey,
Turns out both `adapter-transformers` and `transformers` are using two different versions of the library `tokenizers` as their dependent package, which is the source of the conflict. This kind of issue actually has its own name, which is [Dependency Hell](https://en.wikipedia.org/wiki/Dependency_hell).
We've been trying to fix this problem but haven't succeeded yet. Please let us know if you have any suggestion on this. That would be very helpful for other users as well.
Thanks.

**Comment by minhhdvn** [comment]
Hi @loukey  and @CaoHoangTung, 
We have figured out the way to fix this compatibility issue in version `1.0.1` of trankit. Please install the new version with the command: 
`pip install trankit==1.0.1`. 
Thank you.

**Comment by loukey** [comment]
> Hi @loukey and @CaoHoangTung,
> We have figured out the way to fix this compatibility issue in version `1.0.1` of trankit. Please install the new version with the command:
> `pip install trankit==1.0.1`.
> Thank you.

Thank you!  :)

**Comment by ScDor** [comment]
Thanks!

Any chance to add this to the installation/usage instructions?

**Comment by minhhdvn** [comment]
Thanks for your suggestion, @ScDor. 
We have added the instructions to the [README](https://github.com/nlp-uoregon/trankit#fixing-the-compatibility-issue-of-trankit-with-transformers) and the [documentation page](https://trankit.readthedocs.io/en/latest/installation.html#fixing-the-compatibility-issue-of-trankit-with-transformers).
