### ISSUE TITLE
Does trankit support code-mixed languages (Two languages in one sentence)

### ISSUE THREAD

**Issue by hithesh-sankararaman** [nlp-uoregon/trankit#64]
For example, 
I have a sentence "ah madam எனக்கு G T six fifty test drive பண்ணமுடியுமா madam."
The above text comprises of tamil and english.
Will trankit perform correct pos-tagging when used in "auto" mode. ?

**Comment by minhhdvn** [comment]
Hi @hithesh-sankararaman ,
Thanks for your question.
Trankit models are trained for individual languages and not trained in code-mixed settings.
You can still use Trankit to process code-mixed text, however the result might not be correct.
