### ISSUE TITLE
While importing trankit getting mutable default error 

### ISSUE THREAD

**Issue by ArvinGoyal** [nlp-uoregon/trankit#76]
Hi 
I have installed trankit fist time and while importing it I am gettign below error message:
"ValueError: mutable default <class 'trankit.adapter_transformers.adapter_config.InvertibleAdapterConfig'> for field invertible_adapter is not allowed: use default_factory"

My Python version is 3.11.3

Regards,
Arvin Goyal

**Comment by minhhdvn** [comment]
Hi @ArvinGoyal,
It seems that the issue has something to do with Python 3.11.3.
Please lower your Python version to 3.6/3.7/3.8/3.9/3.10 to fix the issue if it is possible.
Thanks
